/*
 * File: app/view/BusinessList.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CitySearch.view.BusinessList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.businessList',

    config: {
        store: 'hotelId',
        itemTpl: [
            '<img class="photo" src ="http://src.sencha.io/40/{photo_url}" align ="left" style="margin-right:5px;" />',
            '{name}<br/>',
            '<img src="{rating_img_url_small}" /> &nbsp;',
            '<small>{address1} </small>'
        ]
    }

});