/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CitySearch.controller.Main', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            filterfield: '#searchfield'
        },

        control: {
            "searchfield#searchField": {
                keyup: 'onSearchFieldKeyup',
                change: 'onSearchFieldChange'
            }
        }
    },

    onSearchFieldKeyup: function(textfield, e, eOpts) {

        if (e.event.keyCode == 13) {
            this.onSearch(textfield.getValue());
        }
    },

    onSearchFieldChange: function(textfield, newValue, oldValue, eOpts) {
        this.onSearch(newValue);
    },

    onSearch: function(searchterm) {
        var baseUrl = "http://api.yelp.com/business_review_search?ywsid=6djP8TRGT_8JrGgJOsdwYQ";

        var stores = [
        {
            store: Ext.getStore('hotelId'),
            url: baseUrl + '&term=hotels' 
        },
        {
            store: Ext.getStore('restId'),
            url: baseUrl + '&term=restaurants'
        }, 
        {
            store: Ext.getStore('shopId'),
            url: baseUrl + '&term=shops'
        }
        ];

        for (var i=0; i<stores.length; i++) {
            stores[i].store.setProxy({
                type: 'jsonp',
                url: stores[i].url + '&location=' + searchterm,
                reader: {
                    type: 'json',
                    rootProperty: 'businesses'
                }
            });
            stores[i].store.load();
        }

    }

});